spring:
  application:
    name: dragons
  hello: ????
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: dev
  hello: ????
server:
  port: 8083
---
spring:
  config:
    activate:
      on-profile: local
  hello: ????
server:
  port: 8089
---
