spring:
  application:
    name: dragons
  config:
    import:
      - logging.yml
      - optional:redis.yml
      - jpa.yml
  port: 8080
datasource:
  redis:
    enabled: false
springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html
---
spring:
  config:
    activate:
      on-profile: dev
  hello: ????
server:
  port: 8083
---
spring:
  config:
    activate:
      on-profile: local
  hello: ????
server:
  port: 8089
---
