spring:
  application:
    name: dragons
  config:
    import:
      - logging.yml
      - redis.yml
  port: 8080
---
spring:
  config:
    activate:
      on-profile: dev
  hello: ????
server:
  port: 8083
---
spring:
  config:
    activate:
      on-profile: local
  hello: ????
server:
  port: 8089
---
